// GENERATED by synapse-deploy tools/mas-fourier-lines.py --tc, from the
// Sign-In Map's store: Fourier's intro, the same bubbles as MAS's start page
// (pages/index.html). Do not edit by hand: change the copy on the map and
// regenerate.
export const FOURIER_INTRO: readonly string[] = [
  "Hi, I'm Fourier, 41chan's resident signal-processing spirit!",
  "Matrix can be a bit confusing, but don't worry, I'm here to help.",
  "New here? There's a link to create a new account on the next page.",
]
