// The sign-in landing opens doors; it does not walk anyone through anything.
//
// Operator, 2026-09-27: "Tc's onboarding is *replaced* with these MAS changes.
// It's moving Fourier's instructions from before the login flow, onto the
// login flow itself." Fourier-chan now speaks on the MAS pages (synapse-deploy
// mas/templates). These read the source: they catch the walkthrough returning
// and the Create account door losing its way to MAS's register page.
import { readFileSync, existsSync } from 'node:fs'

let failures = 0
function check(name: string, cond: boolean, extra?: unknown) {
  if (cond) console.log('  ok   ' + name)
  else { failures++; console.log('  FAIL ' + name, extra ?? '') }
}
const src = (p: string) => readFileSync(new URL('../src/' + p, import.meta.url), 'utf8')

const landing = src('onboarding/AuthLanding.tsx')
check('the guided walkthrough is gone from the landing', !/GuidedFlow|FourierChan|'guided'/.test(landing))
check('and from the tree', !existsSync(new URL('../src/onboarding/GuidedFlow.tsx', import.meta.url)) &&
  !existsSync(new URL('../src/onboarding/FourierChan.tsx', import.meta.url)))
check('Create account asks for the register page, Log in for the login page',
  /onClick=\{\(\) => onProceed\('create'\)\}/.test(landing) && /onClick=\{\(\) => onProceed\(\)\}/.test(landing))
check('App hands the intent to login', /<AuthLanding onProceed=\{\(intent\) => login\(intent\)\} \/>/.test(src('App.tsx')))
const authz = src('client/oidcAuthorize.ts')
check('the authorize request carries prompt=create only when asked',
  /\.\.\.\(opts\.prompt \? \{ prompt: opts\.prompt \} : \{\}\)/.test(authz))
check('login passes its intent through as the prompt', /prompt: intent,/.test(src('client/ClientContext.tsx')))

console.log('== her intro is on the landing (operator, 2026-09-27)')
// Both doors skip MAS's start page, where the intro is said, so the landing
// says it; the copy is generated from the Sign-In Map by synapse-deploy.
check('the landing says FOURIER_INTRO through FourierSay, above the doors',
  /<FourierSay lines=\{FOURIER_INTRO\} \/>/.test(landing) &&
  landing.indexOf('<FourierSay') < landing.indexOf("onProceed('create')"))
const intro = src('onboarding/fourierIntro.ts')
check('the intro is the generated copy, not hand-written',
  /^\/\/ GENERATED by synapse-deploy tools\/mas-fourier-lines\.py --tc/.test(intro))
{
  const { FOURIER_INTRO } = await import('../src/onboarding/fourierIntro.ts')
  check('and it has lines, every one of them non-empty ASCII',
    FOURIER_INTRO.length > 0 && FOURIER_INTRO.every((l: string) => l.trim().length > 0 && /^[\x20-\x7e]+$/.test(l)))
  check('she says it as herself: "Fourier", never "Fourier-chan"', !FOURIER_INTRO.some((l: string) => /Fourier-chan/.test(l)))
  const { bubbleWait, FIRST_BUBBLE_MS } = await import('../src/onboarding/fourierRun.ts')
  check('her pace is the MAS pages\' pace: 300ms, then 450ms + 16ms a character, at most 1.8s',
    FIRST_BUBBLE_MS === 300 && bubbleWait('') === 450 && bubbleWait('x'.repeat(10)) === 610 && bubbleWait('x'.repeat(500)) === 1800)
}
const say = src('onboarding/FourierSay.tsx')
check('the run plays once and not under reduced motion: it starts said-all when motion is reduced',
  /useState\(\(\) => \(still \? lines\.length : 0\)\)/.test(say))
check('the avatar slides by transform only', /el\.animate\(\[\{ transform: `translateY\(/.test(say))
const css = src('onboarding/fourierSay.css')
check('an unsaid bubble keeps its space (opacity, not display or visibility)',
  /\.fc-say \[data-fc-pending\] \{ opacity: 0; \}/.test(css) && !/display: none|visibility: hidden/.test(css))
check('only the bubble she is saying has the arrow', /\.fc-line\[data-speaks\] \.fc-bubble::before/.test(css))

if (failures) { console.log(`\n${failures} check(s) failed`); process.exit(1) }
console.log('\nauth landing: all checks passed')
